[package]
name = "rscan"
version = "0.1.0"
authors = ["egoroff <egoroff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5"
humantime = "2.1"
walkdir = "2"